import { Router } from "express";
import { userRouter } from "./userRouter.js";
import { carRouter } from "./carRouter.js";
import { sellerRouter } from "./sellerRouter.js";
import { feedbackRouter } from "./feedbackRouter.js";
const indexRoute = Router();
indexRoute.use("/user", userRouter);
indexRoute.use("/boughtcar", carRouter);
indexRoute.use("/seller", sellerRouter);
indexRoute.use("/feedbacks", feedbackRouter);
export default indexRoute;
